FROM debezium/connect:2.7
COPY ./.docker/confluentinc-kafka-connect-elasticsearch-14.1.0/lib/ /kafka/connect/kafka-connect-jdbc/
RUN mkdir -p /kafka/connect/kafka-connect-jdbc/ && \
    curl -L -o /kafka/connect/kafka-connect-jdbc/confluentinc-kafka-connect-elasticsearch-14.1.0.zip \
    https://github.com/confluentinc/kafka-connect-elasticsearch/archive/refs/tags/v14.1.0.zip && \
    unzip /kafka/connect/kafka-connect-jdbc/confluentinc-kafka-connect-elasticsearch-14.1.0.zip -d /kafka/connect/kafka-connect-jdbc/ && \
    rm /kafka/connect/kafka-connect-jdbc/confluentinc-kafka-connect-elasticsearch-14.1.0.zip